# -*- coding: utf-8 -*-
"""Survival Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0_-dYkGCDESuCh5-hqAWmvfc2wvv-RL
"""

def calculate_duration(age_years, units):
    # Constants for conversions
    MONTHS_IN_YEAR = 12
    WEEKS_IN_YEAR = 52.1429  # Average weeks in a year
    DAYS_IN_YEAR = 365.25  # Average including leap years
    HOURS_IN_DAY = 24
    MINUTES_IN_HOUR = 60
    SECONDS_IN_MINUTE = 60

    durations = {}

    # Calculate each duration based on the selected units
    if 'years' in units:
        durations['years'] = age_years
    if 'months' in units:
        durations['months'] = age_years * MONTHS_IN_YEAR
    if 'weeks' in units:
        durations['weeks'] = age_years * WEEKS_IN_YEAR
    if 'days' in units:
        durations['days'] = age_years * DAYS_IN_YEAR
    if 'hours' in units:
        durations['hours'] = age_years * DAYS_IN_YEAR * HOURS_IN_DAY
    if 'minutes' in units:
        durations['minutes'] = age_years * DAYS_IN_YEAR * HOURS_IN_DAY * MINUTES_IN_HOUR
    if 'seconds' in units:
        durations['seconds'] = age_years * DAYS_IN_YEAR * HOURS_IN_DAY * MINUTES_IN_HOUR * SECONDS_IN_MINUTE

    return durations

def display_durations(durations):
    print("\nThe duration lived is:")
    for unit, value in durations.items():
        print(f"{value:,.2f} {unit}")

def main():
    print("Survival Duration Calculator")
    age_years = float(input("Enter age in years: "))

    print("Select the units for the duration (comma-separated list):")
    print("Options: years, months, weeks, days, hours, minutes, seconds")
    units_input = input("Units: ").lower()
    units = [unit.strip() for unit in units_input.split(',')]

    durations = calculate_duration(age_years, units)
    display_durations(durations)

if __name__ == "__main__":
    main()